"use client";

import Link from "next/link";
import Accent from "@/components/primitives/Accent";
import Container from "@/components/primitives/Container";
import Eyebrow from "@/components/primitives/Eyebrow";
import CtaPill from "@/components/sections/quantum/CtaPill";
import { useScrollReveal } from "@/components/primitives/motion/useScrollReveal";
import { CHAPTERS, CLOSING, QUESTIONS } from "@/components/sections/about/aboutContent";

// The rail column keeps carrying a year, and it is the last chapter's — read
// from the data for the same reason the hero's span is.
const LAST_YEAR = CHAPTERS[CHAPTERS.length - 1].year;

// §3 of variant A — the refrain, and the close.
//
// The three questions are the last chapter's, lifted out. They are also the
// first chapter's: two people asking who owns the thing they are building. The
// page's shape is a circle, and this section is where the circle shuts.
//
// ── Why the rail geometry survives into the close ──────────────────────────
// The section is on ink and the rail is gone, but the columns are the rail's:
// the numbers sit where the years sat, the questions sit where the prose sat.
// A closing section that abandoned the grid would read as a different page
// stapled on, which is exactly what a CTA block usually is. Here the apparatus
// keeps running while the argument stops.
//
// The questions are an `<ol>` and the numbers are rendered rather than
// generated by a counter: the reader is meant to be able to count them, and
// three is the number that makes the refrain a refrain.

export default function ClosingRefrain() {
  const rootRef = useScrollReveal<HTMLElement>({ start: "top 78%" });

  return (
    <section
      ref={rootRef}
      data-nav-dark
      className="bg-ink pb-[16svh] pt-[14svh] text-cream"
    >
      <Container>
        <div className="grid-ds gap-y-10">
          <div data-reveal className="col-span-12 lg:col-span-2">
            <Eyebrow className="text-cream/45">The refrain</Eyebrow>
          </div>

          <ol className="col-span-12 flex flex-col lg:col-span-8 lg:col-start-4">
            {QUESTIONS.map((question, i) => (
              <li key={question} data-reveal className="border-t border-white/12 py-8 first:border-t-0 first:pt-0">
                <p className="text-caption-mono text-cream/45">
                  {String(i + 1).padStart(2, "0")}
                </p>
                <p className="mt-4 max-w-[26ch] text-h3 text-cream text-pretty">{question}</p>
              </li>
            ))}
          </ol>
        </div>

        <div className="grid-ds mt-[14svh] gap-y-10">
          <div data-reveal className="col-span-12 lg:col-span-2">
            <p className="text-caption-mono text-cream/45">{LAST_YEAR}</p>
          </div>

          <div className="col-span-12 lg:col-span-8 lg:col-start-4">
            <h2 data-reveal className="max-w-[20ch] text-h1 text-cream text-balance">
              The goal remains the <Accent>same</Accent> as it was in the beginning
            </h2>

            <p data-reveal className="mt-8 max-w-[46ch] text-body-lg text-cream/70 text-pretty">
              {CLOSING.body}
            </p>

            <div data-reveal className="mt-12 flex flex-wrap items-center gap-x-8 gap-y-5">
              <CtaPill href={CLOSING.primary.href} tone="solid" external>
                {CLOSING.primary.label}
              </CtaPill>
              {/* `next/link` and not a `CtaPill`: this destination is internal,
                  and the pill always renders a plain `<a>`. Two pills side by
                  side would also give the pair no hierarchy. */}
              <Link
                href={CLOSING.secondary.href}
                className="text-label-lg text-cream underline underline-offset-4 decoration-white/40 transition-colors hover:decoration-cream focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-cream"
              >
                {CLOSING.secondary.label}
              </Link>
            </div>
          </div>
        </div>
      </Container>
    </section>
  );
}
